all:
  children:
    standard:
      hosts:
        images.rdoproject.org:
          public_address: 38.145.33.168
        logs.rdoproject.org:
          public_address: 38.145.32.13
        lists.rdoproject.org:
          public_address: 38.145.33.193
        registry.rdoproject.org:
          public_address: 38.145.32.81
        www.rdoproject.org:
          public_address: 38.145.32.152
    review:
      hosts:
        managesf.review.rdoproject.org:
          ansible_host: 38.145.34.29
          public_address: 38.145.34.29
        zm01.review.rdoproject.org:
          ansible_host: 38.145.34.44
          public_address: 38.145.34.44
        zm02.review.rdoproject.org:
          ansible_host: 38.145.34.3
          public_address: 38.145.34.3
        nb01.review.rdoproject.org:
          ansible_host: 192.168.240.4
          public_address: 38.145.33.196
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@38.145.34.29"'
        zl01.review.rdoproject.org:
          ansible_host: 192.168.240.7
          public_address: 38.145.33.196
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@38.145.34.29"'
    dlrn:
      hosts:
        trunk.rdoproject.org:
          ansible_port: 3300
          public_address: 54.81.116.189
        delorean.ci.centos.org:
          public_address: 8.43.84.199
        dlrn-builder.rdoproject.org:
          public_address: 38.145.32.81
        dlrn-db.rdoproject.org:
          public_address: 38.145.32.146
    cico:
      vars:
        public_address: 8.43.84.199
        # This would work if there was a way to dynamically declare the user for the jump box
        # See contrib/ssh_config instead
        # ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q user@jump.ci.centos.org"'
      hosts:
        rdo-jenkins-2.ci.centos.org:
          ansible_host: rdo-jenkins-2.ci.centos.org
        rdo-ci-cloudslave01.ci.centos.org:
          ansible_host: 172.19.4.18
        rdo-ci-cloudslave02.ci.centos.org:
          ansible_host: 172.19.4.27
        rdo-ci-cloudslave03.ci.centos.org:
          ansible_host: 172.19.4.29
        rdo-ci-cloudslave04.ci.centos.org:
          ansible_host: 172.19.4.16
        rdo-ci-cloudslave05.ci.centos.org:
          ansible_host: 172.19.4.12
    monitoring:
      hosts:
        master.monitoring.rdoproject.org:
          ansible_port: 3300
          public_address: 46.231.133.98
    monitoring_clients:
      children:
        standard:
        review:
        dlrn:
        cico:
