all:
  children:
    standard:
      hosts:
        images.rdoproject.org:
          public_address: 38.145.33.168
        logs.rdoproject.org:
          public_address: 38.145.32.13
        lists.rdoproject.org:
          public_address: 38.145.33.195
        # future MM3 machine
        future.lists.rdoproject.org:
          ansible_host: 38.145.33.193
          public_address: 38.145.33.193
        www.rdoproject.org:
          public_address: 38.145.32.152
        rdo-web-builder.int.osci.io:
        afs-mirror.rdoproject.org:
          public_address: 38.145.32.16
        codesearch.rdoproject.org:
          public_address: 38.145.33.240
    review:
      hosts:
        managesf.review.rdoproject.org:
          ansible_host: 38.145.34.29
          public_address: 38.145.34.29
    # openshift-ansible requires a specific naming nomenclature
    # We're doing an all-in-one setup so let's keep things simple
    openshift:
      hosts:
        registry.rdoproject.org:
          public_address: 38.145.32.81
          openshift_node_group_name: node-config-all-in-one
          openshift_schedulable: true
    masters:
      children:
        openshift:
    nodes:
      children:
        openshift:
    etcd:
      children:
        openshift:
    OSEv3:
      children:
        masters:
        nodes:
        etcd:
    dlrn:
      hosts:
        trunk.rdoproject.org:
          ansible_port: 3300
          public_address: 3.87.151.16
    dlrndb_replica:
      hosts:
        backup.rdoproject.org:
          ansible_port: 3300
          public_address: 54.82.121.165
    backup:
      hosts:
        backup.rdoproject.org:
          ansible_port: 3300
          public_address: 54.82.121.165
    sfproject:
      hosts:
        softwarefactory-project.io:
        koji.softwarefactory-project.io:
    cico:
      vars:
        public_address: 8.43.84.199
        # This would work if there was a way to dynamically declare the user for the jump box
        # See contrib/ssh_config instead
        # ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q user@jump.ci.centos.org"'
      hosts:
        rdo-ci-cloudslave01.ci.centos.org:
          ansible_host: 172.19.4.105
        rdo-ci-cloudslave02.ci.centos.org:
          ansible_host: 172.19.4.110
        rdo-ci-cloudslave03.ci.centos.org:
          ansible_host: 172.19.4.106
        rdo-ci-cloudslave04.ci.centos.org:
          ansible_host: 172.19.4.102
        rdo-ci-cloudslave05.ci.centos.org:
          ansible_host: 172.19.4.112
    osci_zone:
      # OSCI services parameters are managed in group_vars by OSAS
      # these are RDO-specific parameters
      vars:
        enable_epel_repo: true
        ntp_servers: "{{ osci.ntp }}"
        mail_forwarder: "{{ osci.mail_forwarder }}"
      children:
        osci_internal_zone:
          hosts:
            rdo-web-builder.int.osci.io:

    upgrade_noauto:
      hosts:
        # known issues with the afs driver
        afs-mirror.rdoproject.org:
        # know issues with SF
        managesf.review.rdoproject.org:
        # know issues with SF, mismatches between OpenShift version and OS
        registry.rdoproject.org:
        # know issues with SF
        softwarefactory-project.io:
        # know issues with SF
        koji.softwarefactory-project.io:

    pet_instances:
      hosts:
        # mirror of RHOSP content
        rcm-share:
          ansible_host: 38.145.34.141
