standard:
  hosts:
    images.rdoproject.org:
      public_address: 38.145.33.168
    logs.rdoproject.org:
      public_address: 38.145.32.13
    lists.rdoproject.org:
      public_address: 38.145.33.193
    registry.rdoproject.org:
      public_address: 38.145.32.81
    www.rdoproject.org:
      public_address: 38.145.32.152

review:
  hosts:
    # nodepool-builder does not currently have a WAN IP, see contrib/ssh_config
    nb01.review.rdoproject.org:
      public_address: 46.231.133.218
    review.rdoproject.org:
      public_address: 46.231.133.182
    zm02.review.rdoproject.org:
      # Pending DNS change from zuul-merger02.review.rdoproject.org
      ansible_host: zuul-merger02.review.rdoproject.org
      public_address: 46.231.133.69
    zm03.review.rdoproject.org:
      # Pending DNS change from zuul-merger03.review.rdoproject.org
      ansible_host: zuul-merger03.review.rdoproject.org
      public_address: 46.231.133.57

dlrn:
  hosts:
    trunk.rdoproject.org:
      ansible_port: 3300
      public_address: 54.81.116.189
    delorean.ci.centos.org:
      public_address: 8.43.84.199
    # dlrn-builder doesn't have a DNS yet
    dlrn-builder.rdoproject.org:
      public_address: 38.145.32.81
      ansible_host: 38.145.32.81
    dlrn-db.rdoproject.org:
      public_address: 38.145.32.146

cico:
  vars:
    public_address: 8.43.84.199
  hosts:
    rdo-jenkins-2.ci.centos.org:
    rdo-ci-slave-02.ci.centos.org:
    rdo-ci-slave-03.ci.centos.org:
    rdo-ci-slave-04.ci.centos.org:
    rdo-ci-slave-05.ci.centos.org:

monitoring:
  hosts:
    master.monitoring.rdoproject.org:
      ansible_port: 3300
      public_address: 46.231.133.98

monitoring_clients:
  chlidren:
    standard:
    review:
    dlrn:
    cico:

all:
  vars:
    # We will enable these later, they control the SSH port and security
    discover_ssh: false
    manage_ssh: false
  children:
    standard:
    review:
    dlrn:
    cico:
    monitoring:
