- name: Install dependencies
  include: install.yml
  static: no

- name: Set up checks
  include: checks.yml
  static: no

- name: Sanity check sensu components
  include: sanity-check.yml
  static: no
