# Flush handlers before running sanity checks
- name: Ensure handlers have been flushed before running sanity checks
  meta: flush_handlers

- name: Sanity check Sensu Server components
  command: "{{ item }}"
  changed_when: false
  when: "'monitoring' in group_names"
  with_items:
    - "/opt/sensu/embedded/bin/check-process.rb -p 'rabbitmq' -C 1"
    - "/opt/sensu/embedded/bin/check-process.rb -p 'rdobot' -C 1"
    - "/opt/sensu/embedded/bin/check-process.rb -p 'sensu-api' -C 1"
    - "/opt/sensu/embedded/bin/check-process.rb -p 'sensu-server' -C 1"
    - "/opt/sensu/embedded/bin/check-uchiwa-health.rb -h 'localhost:3000/uchiwa' -u rdo -p rdo"
    - "/opt/sensu/embedded/bin/check-process.rb -p 'httpd' -C 1"

- name: Sanity check Sensu Client components
  command: "{{ item }}"
  changed_when: false
  when: "'monitoring_clients' in group_names"
  with_items:
    - "/opt/sensu/embedded/bin/check-process.rb -p 'sensu-client' -C 1"
    - "/opt/sensu/embedded/bin/check-cpu.rb"
    - "/opt/sensu/embedded/bin/check-load.rb"
    - "/opt/sensu/embedded/bin/check-disk-usage.rb"
    - "/opt/sensu/embedded/bin/check-fstab-mounts.rb"
    - "/opt/sensu/embedded/bin/check-dns.rb -d 'rdoproject.org'"
