---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#


- name: Create /var/www/html/images
  file:
    path:  /var/www/html/images
    state: directory
    mode: 0755
    owner: uploader
    group: uploader
    setype: httpd_sys_content_t

- name: Deploy vhost file
  template:
    src: images.rdoproject.org.conf.j2
    dest: /etc/httpd/conf.d/images.rdoproject.org.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart httpd

- name: Enable and start httpd
  service:
    name: "httpd"
    state: "started"
    enabled: "yes"

- name: Deploy image pruner script
  copy:
    src: prune_tripleo_images.sh
    dest: /usr/local/bin/prune_tripleo_images.sh
    owner: root
    group: root
    mode: 0755

- name: Create cron job to run the pruner script
  cron:
    name: prune_tripleo_images
    minute: 0
    hour: 1
    user: root
    job: '/usr/local/bin/prune_tripleo_images.sh'

- name: Create base directories for images
  file:
    path: "/var/www/html/images/{{ item }}/"
    state: directory
    mode: 0755
    owner: uploader
    group: uploader
    setype: httpd_sys_content_t
  with_items:
    - centos7
    - fedora28

- name: Create old base directories for CentOS 7 images
  file:
    path: "/var/www/html/images/{{ item }}/delorean"
    state: directory
    mode: 0755
    owner: uploader
    group: uploader
    setype: httpd_sys_content_t
  with_items: "{{ centos7_releases }}"

- name: Create symlink from rdo_trunk to delorean (CentOS 7)
  file:
    path: "/var/www/html/images/{{ item }}/rdo_trunk"
    src: "/var/www/html/images/{{ item }}/delorean"
    state: link
  with_items: "{{ centos7_releases }}"

- name: Create symlink from base directory to old base (CentOS 7)
  file:
    path: "/var/www/html/images/centos7/{{ item }}"
    src: "/var/www/html/images/{{ item }}"
    state: link
  with_items: "{{ centos7_releases }}"

- name: Create delorean directory for fedora28
  file:
    path: "/var/www/html/images/fedora28/{{ item }}/delorean"
    state: directory
    mode: 0755
    owner: uploader
    group: uploader
    setype: httpd_sys_content_t
  with_items: "{{ fedora28_releases }}"

- name: Create symlink from rdo_trunk to delorean
  file:
    path: "/var/www/html/images/fedora28/{{ item }}/rdo_trunk"
    src: "/var/www/html/images/fedora28/{{ item }}/delorean"
    state: link
  with_items: "{{ fedora28_releases }}"
