---
- name: Create group for rcm-share
  group:
    name: "{{ rcm_user }}"

- name: Create user dedicated for rcm-share
  user:
    name: "{{ rcm_user }}"
    group: "{{ rcm_user }}"

- name: "Allow Apache to listen on tcp port {{ rcm_vhost_port }}"
  seport:
    ports: "{{ rcm_vhost_port }}"
    proto: tcp
    setype: http_port_t
    state: present

# NOTE: some TripleO scripts are using /mnt/rcm-gest path.
- name: Create symlink (needed for the push script)
  file:
    src: /var/www/html/images/rhel
    dest: /mnt/rcm-guest
    owner: "{{ rcm_user }}"
    group: "{{ rcm_user }}"
    state: link

- name: Create the rcm dir and allow apache to read content
  file:
    path: /var/www/html/images/rhel
    state: directory
    mode: 0750
    owner: "{{ rcm_user }}"
    group: "apache"
    recurse: yes
    setype: httpd_sys_content_t

- name: Configure httpd vhost
  template:
    src: rcm_vhost.j2
    dest: /etc/httpd/conf.d/rcm.vhost.conf
  notify:
    - Restart httpd

- name: Allow RDO cloud floating IP access
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: tcp
    destination_port: "{{ rcm_vhost_port }}"
    src_range: "{{ rdo_floating_ips }}"

- name: Create purge-script
  vars:
    base_dir: /var/www/html/images/rhel/images/redhat8
  template:
    src: purge-images.sh.j2
    dest: /usr/local/bin/purge-rcm-images.sh
    mode: 0755

- name: Create cron job to run the rcm pruner script
  cron:
    name: prune_rcm_images
    minute: 0
    hour: 2
    user: "{{ rcm_user }}"
    job: '/usr/local/bin/purge-rcm-images.sh'
