---
fqdn: microshift.dev
# NOTE: To deploy Microshift > 4.8, you should provide pull-secret.txt content.
# It can be generated here: https://cloud.redhat.com/openshift/create/local
openshift_pull_secret: ""
registry_secret_path: /etc/crio/openshift-pull-secret
disable_selinux: false
hide_sensitive_logs: true
setup_tools: true
disable_swap: true
firewalld_rules_permament: true

use_copr_microshift: false
microshift_version: 4.12

setup_olm: false
repo_dir: "~{{ ansible_user }}/repos"
operator_sdk_version: "v1.21.0"
operator_sdk_url: "https://github.com/operator-framework/operator-sdk"

create_pv: true
pv_storageclass: local-storage
pv_host_path: "/mnt/data"
pv_count:
  start: 1
  end: 15

# This defines a Subject (by creating a client cert), a Namespace and a RoleBinding using role.
certs_dir: "~{{ ansible_user }}/.certs"
standard_user:
  name: dev-admin
  namespace: dev-admin
  role: admin

delete_openshift_storage: true
overwrite_container_policy: false
