---
# NOTE: Tasks in that role are taken from playbooks/registry-renew-certificates.
- name: Check if registry_host is defined
  fail:
    msg: "registry_host is not defined!"
  when: registry_host is not defined

# TODO: Only scale down the router if one of the certificates has been
# updated.
# We need to temporarily scale down the router pod.
# This allows certbot to bind port 80/443
- name: Scale down router pod
  oc_scale:
    name: router
    kind: dc
    namespace: default
    replicas: 0
    state: present

- name: Pause for router to settle
  pause:
    seconds: 5

- name: Renew certificates
  command: certbot renew

- name: Scale up router pod
  oc_scale:
    name: router
    kind: dc
    namespace: default
    replicas: 1
    state: present

- name: Pause for router to settle
  pause:
    seconds: 5
