# TODO exact copy of the code on the old server, need improvement

- name: "Create user for stats downloader"
  user:
    name: "{{ downloader_user }}"
    comment: "Stats downloader user"
    home: "{{ download_dir }}"
    system: yes

- name: "Ensure permissions for stats downloader user directory"
  file:
    name: "{{ download_dir }}"
    state: directory
    mode: 0755

- name: "Install dependencies for scripts"
  package:
    pkg: "{{ item }}"
    state: present
  with_items:
  - perl-DateTime
  - perl-File-chdir
  - wget

- name: "Create subdirectories"
  file:
    path: "{{ download_dir }}/{{ item }}"
    state: directory
    owner: "{{ downloader_user }}"
    group: "{{ downloader_user }}"
  with_items:
  - resolved

- name: "Install scripts"
  template:
    src: "{{ item }}"
    dest: "{{ download_dir }}/{{ item }}"
    mode: 0755
  with_items:
  - fetch_logs.pl
  - logresolve.pl

- name: "Setup crontab"
  cron:
    user: "{{ downloader_user }}"
    hour: 9
    minute: 0
    name: "fetch logs"
    job: "cd {{ download_dir }} && ./fetch_logs.pl"

