---
- name: Install microshift from Copr
  when: use_copr_microshift
  block:
    - name: Enable copr repository
      become: true
      ansible.builtin.shell: |
        dnf copr enable -y @redhat-et/microshift

    - name: Install microshift package
      become: true
      ansible.builtin.yum:
        name: microshift
        state: present
      notify: Restart Microshift

- name: Install microshift package
  become: true
  ansible.builtin.yum:
    name: microshift
    state: present
    enablerepo: microshift-rpms,microshift-deps-rpms
  notify: Restart Microshift
  when: not use_copr_microshift

- name: Flush handlers
  meta: flush_handlers

- name: Wait for kubeconfig file after deploying Microshift
  become: true
  ansible.builtin.wait_for:
    path: /var/lib/microshift/resources/kubeadmin/kubeconfig
    search_regex: microshift
    delay: 5
    timeout: 300

- name: Create kube config directory
  ansible.builtin.file:
    path: ~/.kube
    state: directory

- name: Copy kubeconfig
  become: true
  ansible.builtin.copy:
    src: /var/lib/microshift/resources/kubeadmin/kubeconfig
    dest: "~{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
