---
- name: Clone OLM operator-sdk
  ansible.builtin.git:
    repo: "{{ operator_sdk_url }}"
    dest: "{{ repo_dir }}/operator-sdk"
    version: "{{ operator_sdk_version }}"

- name: Build Operator SDK
  community.general.make:
    target: build
    chdir: "{{ repo_dir }}/operator-sdk"

- name: Check if OLM is installed
  ansible.builtin.shell: |
    build/operator-sdk olm status
  register: olm_status
  args:
    chdir: "{{ repo_dir }}/operator-sdk"
  failed_when: olm_status.rc not in [0, 1]

- name: Install OLM with SDK
  ansible.builtin.shell: |
    build/operator-sdk olm install
  args:
    chdir: "{{ repo_dir }}/operator-sdk"
  when: olm_status.rc != 0
