---
- name: Remove storage config if present
  become: true
  file:
    path: ~{{ ansible_user }}/storage.yaml
    state: absent

- name: Ensure that main PV path directory exists
  become: true
  file:
    path: "{{ pv_host_path }}"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    setype: container_file_t
    selevel: s0

- name: Create PV directories
  become: true
  file:
    path: "{{ pv_host_path }}/pv00{{ zj_pv_number }}"
    state: directory
    mode: "0777"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    setype: container_file_t
    selevel: s0
  with_sequence: "{{ pv_count }}"
  loop_control:
    loop_var: zj_pv_number

# FROM: https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage
# It also base on https://github.com/openstack-k8s-operators/install_yamls/blob/master/scripts/gen-crc-pv-kustomize.sh
- name: Add PV
  shell: |
    cat <<EOF >> ~{{ ansible_user }}/storage.yaml
    ---
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: "{{ pv_storageclass }}00{{ zj_pv_number }}"
      labels:
        type: local
    spec:
      storageClassName: "{{ pv_storageclass }}"
      capacity:
        storage: 10Gi
      accessModes:
        - ReadWriteOnce
        - ReadWriteMany
        - ReadOnlyMany
      persistentVolumeReclaimPolicy: Delete
      local:
        path: "{{ pv_host_path }}/pv00{{ zj_pv_number }}"
        type: DirectoryOrCreate
      volumeMode: Filesystem
    EOF
  with_sequence: "{{ pv_count }}"
  loop_control:
    loop_var: zj_pv_number

- name: Run PV manifest
  command: oc apply -f ~{{ ansible_user }}/storage.yaml
