pruner_log_directory: /var/log/openshift_tag_pruner
pruner_extended_whitelist:
  - current-tripleo
  - current-tripleo-rdo
  - current-tripleo-rdo-internal
  - tripleo-ci-testing
  - promoted-components
  - component-ci-testing
  - previous-current-tripleo
pruner_namespaces:
  - name: tripleomaster
    pruner_days: 3
  - name: tripleoussuri
    pruner_days: 3
  - name: tripleotrain
    pruner_days: 3
  - name: tripleotraincentos8
    pruner_days: 3
  - name: tripleostein
    pruner_days: 3
  - name: tripleorocky
    pruner_days: 4
  - name: tripleoqueens
    pruner_days: 4
  - name: tripleopike
    pruner_days: 4
pruner_dlrn_endpoints:
  - api-centos-pike
  - api-centos-queens
  - api-centos-rocky
  - api-centos-stein
  - api-centos-train
  - api-centos-master-uc
  - api-centos8-master-uc
  - api-centos8-ussuri
  - api-centos8-train
  - api-rhel8-master
  - api-rhel8-train
