pruner_log_directory: /var/log/openshift_tag_pruner
pruner_extended_whitelist:
  - current-tripleo
  - current-tripleo-rdo
  - current-tripleo-rdo-internal
  - tripleo-ci-testing
  - promoted-components
  - component-ci-testing
  - previous-current-tripleo
# NOTE: if pruner_days key is not set for entries in pruner_namespaces,
# script will take value from global pruner_days variable.
pruner_namespaces:
  - name: tripleomaster
  - name: tripleomastercentos9
  - name: tripleovictoria
  - name: tripleowallaby
  - name: tripleoussuri
  - name: tripleou
  - name: tripleotrain
  - name: tripleotraincentos8
  - name: testingmaster
  - name: testingussuri
  - name: testingtrain
  - name: ceph
    pruner_days: 365
pruner_dlrn_endpoints:
  - api-centos-train
  - api-centos8-master-uc
  - api-centos8-wallaby
  - api-centos8-victoria
  - api-centos8-ussuri
  - api-centos8-train
pruner_days: 5
