pruner_log_directory: /var/log/openshift_tag_pruner
pruner_extended_whitelist:
  - current-tripleo
  - current-tripleo-rdo
  - current-tripleo-rdo-internal
  - tripleo-ci-testing
  - promoted-components
  - component-ci-testing
  - previous-current-tripleo
# NOTE: if pruner_days key is not set for entries in pruner_namespaces,
# script will take value from global pruner_days variable.
pruner_namespaces:
  - name: tripleomaster
  - name: tripleoussuri
  - name: tripleou
  - name: tripleotrain
  - name: tripleotraincentos8
  - name: tripleostein
  - name: tripleorocky
    pruner_days: 4
  - name: tripleoqueens
    pruner_days: 4
  - name: testingmaster
  - name: testingussuri
  - name: testingtrain
  - name: testrepo
pruner_dlrn_endpoints:
  - api-centos-queens
  - api-centos-rocky
  - api-centos-stein
  - api-centos-train
  - api-centos8-master-uc
  - api-centos8-ussuri
  - api-centos8-train
pruner_days: 3
