pruner_log_directory: /var/log/openshift_tag_pruner
pruner_extended_whitelist:
  - current-tripleo
  - current-tripleo-rdo
  - current-tripleo-rdo-internal
  - tripleo-ci-testing
pruner_namespaces:
  - tripleomaster
  - tripleorocky
  - tripleoqueens
  - tripleopike
pruner_dlrn_endpoints:
  - api-centos-pike
  - api-centos-queens
  - api-centos-rocky
  - api-centos-master-uc
