all:
  vars:
    public_address: 0.0.0.0
  hosts:
    localhost:
      ansible_connection: local
  children:
    standard:
      hosts:
        localhost:
    review:
      hosts:
        localhost:
    openshift:
      hosts:
        localhost:
    masters:
      children:
        openshift:
    nodes:
      children:
        openshift:
          openshift_node_group_name: node-config-all-in-one
          openshift_schedulable: true
    etcd:
      children:
        openshift:
    OSEv3:
      children:
        masters:
        nodes:
        etcd:
    dlrn:
      hosts:
        localhost:
    backup:
      hosts:
        localhost:
    cico:
      hosts:
        localhost:
