- hosts: localhost
  connection: local
  tasks:
    - name: "Add {{ item }} to the inventory"
      add_host:
        name: "{{ item }}"
        groups: "sf"
      loop: "{{ sf_hosts }}"
    - name: "Create local backup directory {{ local_dir }}"
      file:
        path: "{{ local_dir }}"
        state: directory
        mode: 0700
    - name: "Create local bup directory {{ bup_dir }}"
      file:
        path: "{{ bup_dir }}"
        state: directory
        mode: 0700
    - name: Find HEAD file in bup directory
      stat:
        path: "{{ bup_dir }}/HEAD"
      register: bd
    - name: "Bup init"
      command: "bup init"
      environment:
        BUP_DIR: "{{ bup_dir }}"
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
      when: not bd.stat.exists

- hosts: sf
  gather_facts: run_sf_backup
  tasks:
    - name: "Run sf_backup playbook on the remote SF"
      command: "ansible-playbook /var/lib/software-factory/ansible/sf_backup.yml"
      when: run_sf_backup

- hosts: localhost
  connection: local
  tasks:
    - name: "Rsync remote SF to localhost {{ local_dir }}"
      command: "rsync --delete-delay -r {{ item }}:{{ remote_dir }} {{ local_dir }}"    # noqa command-instead-of-module
      loop: "{{ sf_hosts }}"
      changed_when: false
    - name: "Bup index"
      command: "bup index {{ local_dir }}"
      environment:
        BUP_DIR: "{{ bup_dir }}"
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
      changed_when: false
    - name: "Bup save"
      command: "bup save -n {{ sf_hosts[0] }} {{ local_dir }}"
      environment:
        BUP_DIR: "{{ bup_dir }}"
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
      changed_when: false
