---
- name: Restart sysctl service
  become: true
  ansible.builtin.systemd:
    name: systemd-sysctl
    state: restarted

- name: Restart crio
  become: true
  ansible.builtin.systemd:
    name: crio
    state: restarted
    enabled: true

- name: Restart Microshift
  become: true
  ansible.builtin.systemd:
    name: microshift
    state: started
    enabled: true
