---

- hosts: rdo-web-builder.int.osci.io
  vars:
    website_username: web_builder
  tasks:
    - name: Create builder for the website
      include_role:
        name: web_builder
      vars:
        builder_name: "{{ website_name }}"
        builder: "{{ website_builder | default('middleman') }}"
        builder_username: "{{ website_username }}"
        git_url: "{{ website_repo_url }}"
        git_version: master
        # until it is stable enough to spam the team :-)
        cron_error_email: "{{ builder_error_email }}"
    - name: Create builder for the planet
      include_role:
        name: web_builder
      vars:
        builder_name: "{{ planet_name }}"
        builder: planet
        builder_username: web_builder
        git_url: "{{ planet_repo_url }}"
        git_version: master
        rebuild_interval: 1
        # until it is stable enough to spam the team :-)
        cron_error_email: "{{ builder_error_email }}"
        rsync_server: "{{ planet_sync_server }}"
        rsync_user: "{{ hostvars[planet_sync_server]['planet_sync_user'] }}"
        rsync_location: "{{ hostvars[planet_sync_server]['planet_sync_path'] }}"
    - name: Install SMTP forwarding
      include_role:
        name: msmtp
      vars:
        smart_host: "{{ mail_forwarder }}"
        disable_freeipa: true
  tags: websites_builders


- hosts: www.rdoproject.org
  vars:
    use_ssl: True
    force_ssl: True
    use_letsencrypt: True
  tasks:
    - name: create web builder's user
      user:
        name: "{{ websync_user }}"
        comment: "Web Builder User"
    - name: Create vhost for www.rdoproject.org
      include_role:
        name: httpd
        tasks_from: vhost
      vars:
        website_domain: www.rdoproject.org
        document_root: "{{ websync_path }}"
        document_root_group: "{{ websync_user }}"
        server_aliases:
          - rdoproject.org
          - openstack.redhat.com
        redirects:
          - src: "^/blog/(.*)"
            target: "http://blogs.rdoproject.org/$1"
            match: True
          - src: /stats
            target: https://rdo.biterg.io/
        use_mod_speling: True
        # TODO: investigate why unsafe-eval is needed
        content_security_policy: "default-src 'none'; connect-src 'self'; font-src 'self' https://themes.googleusercontent.com; frame-src https://platform.twitter.com https://syndication.twitter.com; img-src 'self' data: https://pbs.twimg.com https://platform.twitter.com https://s1795.t.eloqua.com https://smtrcs.redhat.com https://syndication.twitter.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.syndication.twimg.com https://img.en25.com https://platform.twitter.com https://secure.eloqua.com https://secure.p01.eloqua.com https://static.redhat.com https://www.redhat.com; style-src 'self' 'unsafe-inline' https://platform.twitter.com"
    - name: "Add RDO-specific mod_speling config"
      copy:
        content: "CheckCaseOnly on\n"
        dest: /etc/httpd/conf.d/www.rdoproject.org.conf.d/mod_speling_rdo.conf
      notify: reload httpd
    - name: Install web redirection to RDO Repositories
      include_role:
        name: rdo-infra/redirect_repos
    - name: Create vhost for ask.rdoproject.org
      include_role:
        name: httpd
        tasks_from: vhost
      vars:
        website_domain: ask.rdoproject.org
        redirect: https://ask.openstack.org/en/questions/scope:unanswered/sort:age-desc/page:1/query:rdo/
    - name: Create vhost for docs.rdoproject.org
      include_role:
        name: httpd
        tasks_from: vhost
      vars:
        website_domain: docs.rdoproject.org
        redirect: https://www.rdoproject.org/documentation/
    - name: Install RDO Dashboards
      include_role:
        name: rdo-infra/dashboards
      vars:
        website_domain: dashboards.rdoproject.org
    - name: Generate RDO download stats
      include_role:
        name: rdo-infra/download_stats
    - name: create planet builder's user
      user:
        name: "{{ planet_sync_user }}"
        comment: "Planet Builder User"
    - name: Create vhost for planet.rdoproject.org
      include_role:
        name: httpd
        tasks_from: vhost
      vars:
        website_domain: planet.rdoproject.org
        document_root: "{{ planet_sync_path }}"
        document_root_group: "{{ planet_sync_user }}"
        content_security_policy: "default-src 'none'; img-src *; style-src 'self' 'unsafe-inline'"
    # content is generated with playbooks/inventory.yaml
    - name: Create vhost for inventory.rdoproject.org
      include_role:
        name: httpd
        tasks_from: vhost
      vars:
        website_domain: inventory.rdoproject.org
        document_root: /var/www/inventory.rdoproject.org
        content_security_policy: "default-src 'none'; img-src *; style-src 'self' 'unsafe-inline'"
  tags: websites

