rdo_sensu_client_packages:
  - "@Development tools"
  - python-setuptools
  - python-requests
  - python-devel
  - ruby-devel
  - libffi-devel
  - libxml2-devel
  - openssl-devel

rdo_sensu_plugins:
  cpu-checks:
    creates: "/opt/sensu/embedded/bin/check-cpu.rb"
  process-checks:
    creates: "/opt/sensu/embedded/bin/check-process.rb"
  disk-checks:
    creates: "/opt/sensu/embedded/bin/check-disk-usage.rb"
  filesystem-checks:
    creates: "/opt/sensu/embedded/bin/check-mtime.rb"
  memory-checks:
    creates: "/opt/sensu/embedded/bin/check-ram.rb"
  network-checks:
    creates: "/opt/sensu/embedded/bin/check-ping.rb"
  dns:
    creates: "/opt/sensu/embedded/bin/check-dns.rb"
  http:
    creates: "/opt/sensu/embedded/bin/check-http.rb"
  uptime-checks:
    creates: "/opt/sensu/embedded/bin/metrics-uptime.rb"
  jenkins:
    creates: "/opt/sensu/embedded/bin/check-jenkins.rb"
  load-checks:
    creates: "/opt/sensu/embedded/bin/check-load.rb"
  io-checks:
    creates: "/opt/sensu/embedded/bin/metrics-iostat-extended.rb"
  uchiwa:
    creates: "/opt/sensu/embedded/bin/check-uchiwa-health.rb"

rdo_custom_sensu_plugins:
  - check-delorean-builds.py
  - check-http-file-age.sh

rdo_custom_sensu_handlers:
  - errbot.py
  - cachet.py

rdo_custom_sensu_extensions:
  - filter_disabled_or_silenced.rb
  - filter_check_retry_occurrences.rb

rdo_checks_defaults:
  occurrences: '3'
  interval: '60'
  ttl: '180'
  standalone: false
  subscribers: 'default'
  metric: false
  handlers:
    - 'errbot'
  custom:
    broadcast: '#rdo-dev'
    retry_occurrences: '30'

rdo_checks:
  check-cpu:
    command: '/opt/sensu/embedded/bin/check-cpu.rb'
    occurrences: '10'
  check-load:
    command: '/opt/sensu/embedded/bin/check-load.rb'
    occurrences: '10'
  check-disk-usage:
    command: '/opt/sensu/embedded/bin/check-disk-usage.rb'
  check-ram:
    command: '/opt/sensu/embedded/bin/check-ram.rb'
  check-fstab:
    command: '/opt/sensu/embedded/bin/check-fstab-mounts.rb'
  check-dns:
    command: '/opt/sensu/embedded/bin/check-dns.rb -d rdoproject.org'
