---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

- name: Create the rdo-ml-backup directories
  file:
    path: /root/rdo-ml-backup/backup/ansible/group_vars
    state: directory
    mode: 0755

- name: Deploy the rdo-ml-backup playbook
  copy:
    src: ml-backup.yml
    dest: /root/rdo-ml-backup/backup/ansible/backup.yml
    owner: root
    group: root
    mode: 0644

- name: Deploy the rdo-ml-backup variables
  copy:
    src: ml-all.yml
    dest: /root/rdo-ml-backup/backup/ansible/group_vars/all.yml
    owner: root
    group: root
    mode: 0644

- name: Clone the sf-ops repo
  git:
    repo: "{{ sfops_repository }}"
    dest: /root/sf-ops
    version: "master"
    force: yes

- name: Deploy sf-ops configuration
  copy:
    src: reviewrdo-all.yml
    dest: /root/sf-ops/backup/ansible/group_vars/all.yml
    owner: root
    group: root
    mode: 0644

- name: Check for existing bup binary
  stat:
    path: "/usr/local/bin/bup"
  register: bup_exists

- name: Create temporary directory for bup
  tempfile:
    state: directory
    suffix: bup
  register: bup_path
  when: bup_exists.stat.exists == False

- name: Fetch and uncompress bup tarball
  unarchive:
    src: "https://github.com/bup/bup/archive/{{ bup_version }}.tar.gz"
    dest: "{{ bup_path.path }}"
    remote_src: yes
  when: bup_exists.stat.exists == False

- name: Compile and install bup
  shell:
    cmd: |
      ./configure
      make
      make install
    chdir: "{{ bup_path.path }}/bup-{{ bup_version }}"
  when: bup_exists.stat.exists == False

- name: Create crontab entry for rdo-ml-backup
  cron:
    name: "Run backup for lists.rdo"
    user: root
    minute: "1"
    hour: "7"
    job: 'ansible-playbook /root/rdo-ml-backup/backup/ansible/backup.yml'

- name: Create crontab entry for review-rdo-backup
  cron:
    name: "Run backup for review.rdo"
    user: root
    minute: "0"
    hour: "5"
    day: "*/2"
    job: 'ansible-playbook /root/sf-ops/backup/ansible/backup.yml'

- name: Create the sf-project.io directories
  file:
    path: /root/sf-project-backup/group_vars
    state: directory
    mode: 0755

- name: Deploy the sf-project.io variables
  copy:
    src: sf-project-all.yml
    dest: /root/sf-project-backup/group_vars/all.yml
    owner: root
    group: root
    mode: 0644

- name: Copy backup.yml playbook for sf-project.io
  copy:
    src: /root/sf-ops/backup/ansible/backup.yml
    dest: /root/sf-project-backup/backup.yml
    owner: root
    group: root
    mode: 0644
    remote_src : yes

- name: Add MAILTO address for SF related backups
  cron:
    name: MAILTO
    user: root
    env: yes
    value: softwarefactory-operations-team@redhat.com
    cron_file: sf-backup

- name: Create crontab entry for sf-project.io
  cron:
    name: "Run backup for sf-project.io"
    user: root
    minute: "0"
    hour: "1"
    day: "*/2"
    job: 'ansible-playbook -vv /root/sf-project-backup/backup.yml'
    cron_file: sf-backup

- name: Deploy the koji.sf-project.io variables
  copy:
    src: koji-all.yml
    dest: /root/sf-ops/backup-koji/ansible/group_vars/all.yml
    owner: root
    group: root
    mode: 0644

- name: Create crontab entry for koji.sf-project.io
  cron:
    name: "Run backup for koji.sf-project.io"
    user: root
    minute: "0"
    hour: "3"
    day: "*/2"
    job: 'ansible-playbook -vv /root/sf-ops/backup-koji/ansible/backup.yml'
    cron_file: sf-backup
