---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

- name: Create vgbackup
  lvg:
    vg: vgbackup
    pvs: "{{ vgbackup_disk }}"

- name: Create lvol for review.rdo backup
  lvol:
    vg: vgbackup
    lv: lv_review_rdo
    size: "{{ backup_review_rdo_size }}"

- name: Create lvol for koji.sf.io backup
  lvol:
    vg: vgbackup
    lv: lv_sf_koji
    size: "{{ backup_koji_size }}"

- name: Create lvol for sf.io backup
  lvol:
    vg: vgbackup
    lv: lv_sfbackup
    size: "{{ backup_sfio_size }}"

- name: Create file systems
  filesystem:
    fstype: xfs
    dev: "{{ item }}"
  with_items:
    - /dev/vgbackup/lv_review_rdo
    - /dev/vgbackup/lv_sf_koji
    - /dev/vgbackup/lv_sfbackup

- name: Mount review.rdo backup volume
  mount:
    path: /var/lib/backup_review_rdo
    src: /dev/vgbackup/lv_review_rdo
    fstype: xfs
    opts: noatime
    state: mounted

- name: Mount koji backup volume
  mount:
    path: /var/www/html/sfkoji
    src: /dev/vgbackup/lv_sf_koji
    fstype: xfs
    opts: noatime
    state: mounted

- name: Mount sf.io backup volume
  mount:
    path: /var/lib/sfbackup
    src: /dev/vgbackup/lv_sfbackup
    fstype: xfs
    opts: noatime
    state: mounted
